triggers:
- description: null
  envs: []
  last_enabled_at: 2024-11-10 16:01:04.713303
  name: API_TRIGGER_CREATED_FROM_CODE
  pipeline_uuid: ingest_sf_crime_incidents_historical
  schedule_interval: null
  schedule_type: api
  settings: null
  sla: null
  start_time: 2024-11-10 16:01:04.713269
  status: active
  token: bef5f2cd80d74bad84070947a04956f6
  variables: null
