version: 0.1.1
default:
  # Google
  GOOGLE_SERVICE_ACC_KEY:
    type: service_account
    project_id: project-id
    private_key_id: key-id
    private_key: "-----BEGIN PRIVATE KEY-----\nyour_private_key\n-----END_PRIVATE_KEY"
    client_email: your_service_account_email
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://accounts.google.com/o/oauth2/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/your_service_account_email"
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/path/to/your/service/account/key.json"
  GOOGLE_LOCATION: US # Optional

dev:
  # Google
  # GOOGLE_SERVICE_ACC_KEY:
  #   type: service_account
  #   project_id: "{{ mage_secret_var('project_id') }}"
  #   private_key_id: "{{ mage_secret_var('private_key_id') }}"
  #   private_key: "{{ mage_secret_var('private_key') }}"
  #   client_email: "{{ mage_secret_var('client_email') }}"
  #   auth_uri: "https://accounts.google.com/o/oauth2/auth"
  #   token_uri: "https://accounts.google.com/o/oauth2/token"
  #   auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
  #   client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/{{ mage_secret_var('client_email') }}"
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/home/src/secrets/gcp_credentials.json"
  GOOGLE_LOCATION: US # Optional


